apiVersion: v1
kind: Service
metadata:
        name: mysql
        namespace: dev3
spec:
        selector:
                app: mysql
        ports:
                - port: 3306
        clusterIP: None #Since this is mysql service, we can directly use the IP addr of the POD .
