apiVersion: v1
kind: Service
metadata:
        name: my-backend-service #NGINX proxypass running on the container needs this name
        labels:
                app: backend-restapp
                tier: backend
spec:
        selector:
                app: backend-restapp #traffic will be sent to the POD with this name
        ports:
                - name: http
                  port: 8080 #ClusterIP Service Port
                  targetPort: 8080 #Container Port
