apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      name: app3-pod
      labels:
        app: app3
    spec:
      containers:
      - name: my-helloworld-app
        image: stacksimplify/kubenginx:3.0.0
        ports:
         - containerPort: 80

