apiVersion: v1
kind: Service
metadata: 
        name: frontend-nginx-nodeport-service
        labels:
                app: frontend-nginxapp
                tier: frontend
spec:
        type: NodePort
        selector:
                app: frontend-nginxapp
        ports:
                - name: http
                  port: 80 #clusterIP service port
                  targetPort: 80 #container port
                  nodePort: 31234

